enum StatType {
  str('STR', 'Strength'),
  agi('AGI', 'Agility'),
  vit('VIT', 'Vitality'),
  intl('INT', 'Intelligence'),
  per('PER', 'Perception');

  final String code;
  final String label;
  const StatType(this.code, this.label);

  static StatType fromCode(String code) {
    return StatType.values.firstWhere(
      (e) => e.code.toUpperCase() == code.toUpperCase(),
      orElse: () => StatType.str,
    );
  }
}

class Quest {
  final String id;
  String title;
  String description;
  int current;
  int target;
  String unit;
  StatType statReward;
  int expReward;
  int goldReward;
  bool isDaily;
  bool isCompleted;
  int streak;
  bool isEmergency;
  String? deadline;
  String? urgentReason;

  Quest({
    required this.id,
    required this.title,
    required this.description,
    this.current = 0,
    required this.target,
    this.unit = 'reps',
    this.statReward = StatType.str,
    this.expReward = 50,
    this.goldReward = 50,
    this.isDaily = true,
    this.isCompleted = false,
    this.streak = 0,
    this.isEmergency = false,
    this.deadline,
    this.urgentReason,
  });

  double get progress => target > 0 ? (current / target).clamp(0.0, 1.0) : 0.0;

  Quest copyWith({
    String? id,
    String? title,
    String? description,
    int? current,
    int? target,
    String? unit,
    StatType? statReward,
    int? expReward,
    int? goldReward,
    bool? isDaily,
    bool? isCompleted,
    int? streak,
    bool? isEmergency,
    String? deadline,
    String? urgentReason,
  }) => Quest(
    id: id ?? this.id,
    title: title ?? this.title,
    description: description ?? this.description,
    current: current ?? this.current,
    target: target ?? this.target,
    unit: unit ?? this.unit,
    statReward: statReward ?? this.statReward,
    expReward: expReward ?? this.expReward,
    goldReward: goldReward ?? this.goldReward,
    isDaily: isDaily ?? this.isDaily,
    isCompleted: isCompleted ?? this.isCompleted,
    streak: streak ?? this.streak,
    isEmergency: isEmergency ?? this.isEmergency,
    deadline: deadline ?? this.deadline,
    urgentReason: urgentReason ?? this.urgentReason,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'title': title,
    'description': description,
    'current': current,
    'target': target,
    'unit': unit,
    'statReward': statReward.code,
    'expReward': expReward,
    'goldReward': goldReward,
    'isDaily': isDaily,
    'isCompleted': isCompleted,
    'streak': streak,
    'isEmergency': isEmergency,
    'deadline': deadline,
    'urgentReason': urgentReason,
  };

  factory Quest.fromJson(Map<String, dynamic> json) => Quest(
    id: json['id'] ?? '',
    title: json['title'] ?? '',
    description: json['description'] ?? '',
    current: json['current'] ?? 0,
    target: json['target'] ?? 1,
    unit: json['unit'] ?? 'reps',
    statReward: StatType.fromCode(json['statReward'] ?? 'STR'),
    expReward: json['expReward'] ?? 50,
    goldReward: json['goldReward'] ?? 50,
    isDaily: json['isDaily'] ?? true,
    isCompleted: json['isCompleted'] ?? false,
    streak: json['streak'] ?? 0,
    isEmergency: json['isEmergency'] ?? false,
    deadline: json['deadline'],
    urgentReason: json['urgentReason'],
  );

  /// Creates a dramatic emergency quest spawned by the autonomous system.
  static Quest createEmergencyQuest({
    required String title,
    required String description,
    required int target,
    required String unit,
    required StatType statReward,
    String? urgentReason,
  }) =>
      Quest(
        id: 'emergency_${DateTime.now().millisecondsSinceEpoch}',
        title: title,
        description: description,
        target: target,
        unit: unit,
        statReward: statReward,
        expReward: 200,
        goldReward: 250,
        isDaily: false,
        isEmergency: true,
        deadline: '23:59',
        urgentReason: urgentReason ?? 'Player has demonstrated insufficient discipline.',
      );

  static List<Quest> defaultSoloQuests() => [
    Quest(
      id: 'daily_pushups',
      title: 'Push-ups',
      description: 'Strengthen chest, arms, and core to endure dungeon battles.',
      current: 0,
      target: 100,
      unit: 'reps',
      statReward: StatType.str,
      expReward: 60,
      goldReward: 50,
      isDaily: true,
    ),
    Quest(
      id: 'daily_situps',
      title: 'Curl-ups / Sit-ups',
      description: 'Solidify abdominal defense against monster impact.',
      current: 0,
      target: 100,
      unit: 'reps',
      statReward: StatType.vit,
      expReward: 60,
      goldReward: 50,
      isDaily: true,
    ),
    Quest(
      id: 'daily_squats',
      title: 'Squats',
      description: 'Build lower body explosiveness for high-speed dashes.',
      current: 0,
      target: 100,
      unit: 'reps',
      statReward: StatType.agi,
      expReward: 60,
      goldReward: 50,
      isDaily: true,
    ),
    Quest(
      id: 'daily_running',
      title: '10km Running',
      description: 'Expand lung capacity and limitless stamina.',
      current: 0,
      target: 10,
      unit: 'km',
      statReward: StatType.vit,
      expReward: 100,
      goldReward: 100,
      isDaily: true,
    ),
    Quest(
      id: 'daily_hydration',
      title: 'Hydration Protocol',
      description: 'Maintain peak cellular conductivity and optimal mana flow.',
      current: 0,
      target: 3000,
      unit: 'ml',
      statReward: StatType.vit,
      expReward: 50,
      goldReward: 40,
      isDaily: true,
    ),
    Quest(
      id: 'custom_study',
      title: 'Focused Study / Deep Work',
      description: 'Sharpen cognitive faculties and master complex skills.',
      current: 0,
      target: 60,
      unit: 'mins',
      statReward: StatType.intl,
      expReward: 80,
      goldReward: 80,
      isDaily: true,
    ),
    Quest(
      id: 'custom_meditation',
      title: 'Meditation & Perception',
      description: 'Calm the mind to detect unseen murderous intent and heighten senses.',
      current: 0,
      target: 15,
      unit: 'mins',
      statReward: StatType.per,
      expReward: 50,
      goldReward: 40,
      isDaily: true,
    ),
    Quest(
      id: 'daily_reading',
      title: 'Grimoire / Book Reading',
      description: 'Absorb strategic knowledge and unlock tactical mental frameworks.',
      current: 0,
      target: 30,
      unit: 'mins',
      statReward: StatType.intl,
      expReward: 60,
      goldReward: 50,
      isDaily: true,
    ),
    Quest(
      id: 'daily_cold_shower',
      title: 'Cold Shower Discipline',
      description: 'Forge unbreakable mental fortitude and shock the nervous system into alertness.',
      current: 0,
      target: 5,
      unit: 'mins',
      statReward: StatType.str,
      expReward: 60,
      goldReward: 50,
      isDaily: true,
    ),
    Quest(
      id: 'daily_stretching',
      title: 'Mobility & Stretching',
      description: 'Enhance dynamic flexibility and prevent battlefield tendon strain.',
      current: 0,
      target: 15,
      unit: 'mins',
      statReward: StatType.agi,
      expReward: 50,
      goldReward: 40,
      isDaily: true,
    ),
    Quest(
      id: 'daily_steps',
      title: 'Daily Recon Steps',
      description: 'Maintain continuous tactical movement and ground coverage.',
      current: 0,
      target: 10000,
      unit: 'steps',
      statReward: StatType.agi,
      expReward: 80,
      goldReward: 70,
      isDaily: true,
    ),
    Quest(
      id: 'daily_sleep',
      title: 'Rest & Regeneration',
      description: 'Achieve uninterrupted high-quality sleep for full health and mana recovery.',
      current: 0,
      target: 8,
      unit: 'hours',
      statReward: StatType.vit,
      expReward: 70,
      goldReward: 60,
      isDaily: true,
    ),
  ];

  static List<Quest> presetTemplates() => [
    Quest(
      id: 'tmpl_pushups',
      title: 'Push-ups',
      description: 'Upper body power and chest conditioning.',
      target: 100,
      unit: 'reps',
      statReward: StatType.str,
      expReward: 60,
      goldReward: 50,
    ),
    Quest(
      id: 'tmpl_pullups',
      title: 'Pull-ups / Chin-ups',
      description: 'Vertical pulling strength and back density.',
      target: 25,
      unit: 'reps',
      statReward: StatType.str,
      expReward: 70,
      goldReward: 60,
    ),
    Quest(
      id: 'tmpl_squats',
      title: 'Squats',
      description: 'Leg power and core balance.',
      target: 100,
      unit: 'reps',
      statReward: StatType.agi,
      expReward: 60,
      goldReward: 50,
    ),
    Quest(
      id: 'tmpl_situps',
      title: 'Core & Sit-ups',
      description: 'Abdominal shield and torso stability.',
      target: 100,
      unit: 'reps',
      statReward: StatType.vit,
      expReward: 60,
      goldReward: 50,
    ),
    Quest(
      id: 'tmpl_running',
      title: 'Running / Jogging',
      description: 'Cardiovascular endurance and lung capacity.',
      target: 5,
      unit: 'km',
      statReward: StatType.vit,
      expReward: 80,
      goldReward: 75,
    ),
    Quest(
      id: 'tmpl_hydration',
      title: 'Water Hydration',
      description: 'Daily water intake for energy and recovery.',
      target: 3000,
      unit: 'ml',
      statReward: StatType.vit,
      expReward: 50,
      goldReward: 40,
    ),
    Quest(
      id: 'tmpl_study',
      title: 'Focused Study / Coding',
      description: 'Deep uninterrupted learning or problem solving.',
      target: 60,
      unit: 'mins',
      statReward: StatType.intl,
      expReward: 80,
      goldReward: 80,
    ),
    Quest(
      id: 'tmpl_reading',
      title: 'Book Reading',
      description: 'Expand intellect, vocabulary, and wisdom.',
      target: 30,
      unit: 'mins',
      statReward: StatType.intl,
      expReward: 60,
      goldReward: 50,
    ),
    Quest(
      id: 'tmpl_meditation',
      title: 'Mindfulness & Meditation',
      description: 'Mental clarity, focus, and stress reduction.',
      target: 15,
      unit: 'mins',
      statReward: StatType.per,
      expReward: 50,
      goldReward: 40,
    ),
    Quest(
      id: 'tmpl_cold_shower',
      title: 'Cold Shower',
      description: 'Mental resilience and nervous system activation.',
      target: 5,
      unit: 'mins',
      statReward: StatType.str,
      expReward: 60,
      goldReward: 50,
    ),
    Quest(
      id: 'tmpl_mobility',
      title: 'Mobility & Stretching',
      description: 'Full-body flexibility and posture alignment.',
      target: 15,
      unit: 'mins',
      statReward: StatType.agi,
      expReward: 50,
      goldReward: 40,
    ),
    Quest(
      id: 'tmpl_steps',
      title: 'Daily 10,000 Steps',
      description: 'Active lifestyle and metabolic health.',
      target: 10000,
      unit: 'steps',
      statReward: StatType.agi,
      expReward: 80,
      goldReward: 70,
    ),
    Quest(
      id: 'tmpl_sleep',
      title: '8 Hours Sleep',
      description: 'Restorative recovery and brain replenishment.',
      target: 8,
      unit: 'hours',
      statReward: StatType.vit,
      expReward: 70,
      goldReward: 60,
    ),
    Quest(
      id: 'tmpl_journaling',
      title: 'Evening Journaling',
      description: 'Reflect on daily victories and self-improvement.',
      target: 15,
      unit: 'mins',
      statReward: StatType.per,
      expReward: 50,
      goldReward: 40,
    ),
  ];
}
